### ISSUE TITLE
why you read the file twice?

### ISSUE THREAD

**Issue by coolicer** [beatfreaker/subdownloader#1]
I am a new noder.when I read your source code, I found out the `getHash` method read file twice.

`var s = fs.createReadStream(file, {start: 0, end: (64*1024)-1});`

`var sNew = fs.createReadStream(file, {start: stats['size']-(64*1024), end: stats['size']-1});`

any good point to do like this?

**Comment by beatfreaker** [comment]
It is because the [SubDB API](http://thesubdb.com/api/) I am using  it expects the hash value which is to be composed by taking first and last 64kb of a video file. I didn't know how to calculate it in single read so i used it twice.

`var s = fs.createReadStream(file, {start: 0, end: (64*1024)-1});`

this calculates the first 64kb and below line calculates last 64kb of video file

`var sNew = fs.createReadStream(file, {start: stats['size']-(64*1024), end: stats['size']-1});`

**Comment by coolicer** [comment]
@beatfreaker I think `{start: stats['size']-(64*1024), end: stats['size']-1}` is the rest of the file.Not the last 64kb.

**Comment by beatfreaker** [comment]
@coolicer Nope i don't think so as `{start : stats['size'-(64*1024)]}` this means start position to read the file will be `(total size - 64kb)` so it will be last 64kb isn't it ??

**Comment by coolicer** [comment]
@beatfreaker OK,I see.thx.
